name: bootpay
description: A Bootpay plugin that provides payment api on Android, iOS and Web.

version: 4.9.5

homepage: https://www.bootpay.co.kr
repository: https://github.com/bootpay/bootpay_flutter.git
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  bootpay_webview_flutter: 4.3.2
  bootpay_webview_flutter_android: 3.7.3
  bootpay_webview_flutter_wkwebview: 3.4.2
  
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  js: ^0.6.4
  fluttertoast: ^8.2.5
  http: ^1.2.0
  package_info_plus: ^4.0.2
  encrypt: ^5.0.1
  get: ^4.6.5
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  plugin_platform_interface: ^2.1.3

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: bootpay_webview_flutter_android
      ios:
        default_package: bootpay_webview_flutter_wkwebview
      web:
